# 
# Display settings
# ----------
# line_style : str or None
#     The style of the polygon cell borders.
    
#     Options:
#     - None
#     - Any line style described in matplotlib (see below).
    
# line_width : int
#     The width of the polygon cell borders in pixels.
    
# line_color : str or HEX or RGB
#     The color of the polygon cell borders.
    
# point_type: PointType enum
#     The style of the cell location markers.
    
#     Options:
#     - PointType.NONE - No marker.
#     - PointType.NEIGHBORS - The number of neighbors the cell has as text.
#     - PointType.INDEX - The cell index as text.
#     - PointType.POINT - Any marker style described using point_style.

# point_style: str
#     The style of the cell location markers if point_type is PointType.POINT. 
#     Any marker style described in matplotlib (see below).
              
# point_color : str
#     The color of the cell location markers.
    
# point_size: int
#     The size of cell location markers in pixels.
    
# fill: bool
#     Boolean as to whether the cells should be filled with colors from
#     the neighbor colormap.
    
# neighbor_colormap: str
#     Matplotlib colormap name for labelling number of neighbors (see below)
    
# scale_neighbors: [int int]
#     The low and high number of neighbor values to determine the range of
#     colors used from the colormap. These values will be reflected in the
#     legend.
    
# mask_color: str or HEX or RGB
#     The color of the mask representing the area of interest.

# mask_point_color: str or HEX or RGB
#     The color of the points on the mask representing the area of interest.

# mask_point_size: int
#     The size of the points on the mask representing the area of interest.
# ----------

# Morphological settings
# ----------
# alpha: float or None
#     The alpha value for border generation. Leave as None for the default (ICD).

# dilation_factor: float or None
#     The dilation factor for border generation. Leave as None for the default (0.5 * ICD).
# 

display_settings:
    line_style:           True
    line_width:           1
    line_color:           orange
    ##################################
    point_type:           4 
    point_style:          .
    point_color:          black
    point_size:           3
    ##################################
    fill:                 False
    neighbor_colormap:    Oranges
    scale_neighbors:      
      - 3
      - 10
    ##################################
    mask_color:           #1c995e
    mask_point_color:     w
    mask_point_size:      3
    ##################################
    pdf_bandwidth:        0.1
    grid_density:         500
    contour_levels:       10
    cutoff:               0.4


## Recommended to leave these settings as None unless border creation is failing

morph_settings:
    alpha:                None
    dilation_factor:      None


############ Colormaps

# Accent Accent_r Blues Blues_r BrBG BrBG_r BuGn BuGn_r BuPu 
# BuPu_r CMRmap CMRmap_r Dark2 Dark2_r GnBu GnBu_r Greens Greens_r 
# Greys Greys_r OrRd OrRd_r Oranges Oranges_r PRGn PRGn_r Paired 
# Paired_r Pastel1 Pastel1_r Pastel2 Pastel2_r PiYG PiYG_r PuBu 
# PuBuGn PuBuGn_r PuBu_r PuOr PuOr_r PuRd PuRd_r Purples Purples_r 
# RdBu RdBu_r RdGy RdGy_r RdPu RdPu_r RdYlBu RdYlBu_r RdYlGn 
# RdYlGn_r Reds Reds_r Set1 Set1_r Set2 Set2_r Set3 Set3_r 
# Spectral Spectral_r Wistia Wistia_r YlGn YlGnBu YlGnBu_r YlGn_r 
# YlOrBr YlOrBr_r YlOrRd YlOrRd_r afmhot afmhot_r autumn autumn_r 
# binary binary_r bone bone_r brg brg_r bwr bwr_r cividis cividis_r 
# cool cool_r coolwarm coolwarm_r copper copper_r cubehelix cubehelix_r 
# flag flag_r gist_earth gist_earth_r gist_gray gist_gray_r gist_heat 
# gist_heat_r gist_ncar gist_ncar_r gist_rainbow gist_rainbow_r gist_stern 
# gist_stern_r gist_yarg gist_yarg_r gnuplot gnuplot2 gnuplot2_r gnuplot_r 
# gray gray_r hot hot_r hsv hsv_r inferno inferno_r jet jet_r 
# magma magma_r nipy_spectral nipy_spectral_r ocean ocean_r pink pink_r 
# plasma plasma_r prism prism_r rainbow rainbow_r seismic seismic_r 
# spring spring_r summer summer_r tab10 tab10_r tab20 tab20_r tab20b 
# tab20b_r tab20c tab20c_r terrain terrain_r turbo turbo_r twilight 
# twilight_r twilight_shifted twilight_shifted_r viridis viridis_r winter winter_r

############ Marker styles

# . - point marker  - pixel marker o - circle marker v - triangle_down marker
# ^ - triangle_up marker < - triangle_left marker > - triangle_right marker
# 1 - tri_down marker 2 - tri_up marker 3 - tri_left marker 4 - tri_right marker
# 8 - octagon marker s - square marker p - pentagon marker P - plus (filled) marker
# * - star marker h - hexagon1 marker H - hexagon2 marker + - plus marker
# x - x marker X - x (filled) marker D - diamond marker d - thin_diamond marker
# | - vline marker _ - hline marker

############ Line styles

# - - solid line style -- - dashed line style -. - dash-dot line style : - dotted line style


######  For more info on colors and styles go to https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.plot.html